#!/usr/bin/env python3
"""Builds mcconsole-installer.py: a single-file, dependency-free installer
that bundles the entire cli/ package (pyproject.toml + the mcconsole/
package) as a base64-encoded zip and embeds it in a small bootstrap script.

Usage:
    python3 scripts/build_installer.py [--output PATH]

Same spirit as ezinstaller's own ezi.py bootstrap: one file an end user can
download and run with `python3 mcconsole-installer.py`, no repo checkout or
network access to GitHub required at install time.
"""

from __future__ import annotations

import argparse
import base64
import io
import textwrap
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CLI_DIR = REPO_ROOT / "cli"

EXCLUDED_DIR_NAMES = {"__pycache__", ".venv", "build", "dist"}


def iter_cli_files():
    for path in sorted(CLI_DIR.rglob("*")):
        if not path.is_file():
            continue
        if any(part in EXCLUDED_DIR_NAMES or part.endswith(".egg-info") for part in path.parts):
            continue
        yield path


def build_bundle_zip() -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in iter_cli_files():
            arcname = path.relative_to(CLI_DIR).as_posix()
            zf.write(path, arcname)
    return buffer.getvalue()


BOOTSTRAP_TEMPLATE = '''#!/usr/bin/env python3
"""mcconsole-installer.py — single-file installer for the mcconsole CLI.

Generated by scripts/build_installer.py from the cli/ package — do not
edit by hand, regenerate it instead.

Usage:
    python3 mcconsole-installer.py [install_dir]

Bundles its own copy of the mcconsole CLI source, so this file is all you
need: no repo checkout, no network access beyond PyPI (for prompt_toolkit).
"""

from __future__ import annotations

import argparse
import base64
import os
import subprocess
import sys
import venv
import zipfile
from pathlib import Path

BUNDLE_B64 = """
{bundle_b64}
"""

MOD_JAR_REMINDER = """
Don't forget: the Fabric mod itself still needs to be installed
separately. Grab the built jar from mod/build/libs/ (or a GitHub
release once one exists) and drop it into your Fabric "mods" folder,
then launch Minecraft once before running `mcconsole`.
"""


def check_python_version() -> None:
    if sys.version_info < (3, 10):
        found = ".".join(str(part) for part in sys.version_info[:3])
        print(f"mcconsole requires Python 3.10+, found {{found}}.", file=sys.stderr)
        print("Install a newer Python and re-run this installer with it.", file=sys.stderr)
        sys.exit(1)


def resolve_install_dir(arg: str | None) -> Path:
    if arg:
        return Path(arg).expanduser().resolve()

    default = Path.home() / "apps" / "mcconsole"
    try:
        response = input(f"Install directory [{{default}}]: ").strip()
    except EOFError:
        response = ""
    return Path(response).expanduser().resolve() if response else default


def extract_bundle(install_dir: Path) -> Path:
    zip_path = install_dir / "mcconsole-cli-bundle.zip"
    zip_path.write_bytes(base64.b64decode(BUNDLE_B64))

    src_dir = install_dir / "src"
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(src_dir)

    zip_path.unlink()
    return src_dir


def venv_bin_dir(venv_dir: Path) -> Path:
    return venv_dir / ("Scripts" if os.name == "nt" else "bin")


def create_venv(venv_dir: Path) -> None:
    print(f"Creating virtual environment at {{venv_dir}} ...")
    venv.EnvBuilder(with_pip=True, clear=True).create(venv_dir)


def run(cmd: list[str]) -> None:
    print("+ " + " ".join(cmd))
    subprocess.run(cmd, check=True)


def install_cli(venv_dir: Path, src_dir: Path) -> None:
    pip = str(venv_bin_dir(venv_dir) / ("pip.exe" if os.name == "nt" else "pip"))
    run([pip, "install", "--quiet", "--upgrade", "pip"])
    run([pip, "install", "--quiet", "prompt_toolkit>=3.0.43"])
    run([pip, "install", "--quiet", str(src_dir)])


def add_to_path(bin_dir: Path) -> None:
    export_line = f'export PATH="{{bin_dir}}:$PATH"'

    if os.name == "nt":
        print()
        print("Add the following directory to your PATH (e.g. via System")
        print("Properties -> Environment Variables), then open a new terminal:")
        print(f"  {{bin_dir}}")
        return

    shell = os.environ.get("SHELL", "")
    if "zsh" in shell:
        rc_file = Path.home() / ".zshrc"
    elif "bash" in shell:
        rc_file = Path.home() / ".bash_profile"
        if not rc_file.exists():
            rc_file = Path.home() / ".bashrc"
    else:
        rc_file = None

    marker = "# Added by the mcconsole installer"
    if rc_file is not None:
        try:
            existing = rc_file.read_text() if rc_file.exists() else ""
            if export_line not in existing:
                with rc_file.open("a") as f:
                    f.write(f"\\n{{marker}}\\n{{export_line}}\\n")
                print(f"Added mcconsole to PATH via {{rc_file}} (restart your terminal, or run:")
                print(f"  source {{rc_file}}")
                print(")")
            else:
                print(f"{{rc_file}} already has mcconsole on PATH.")
            return
        except OSError as exc:
            print(f"Could not edit {{rc_file}} automatically ({{exc}}).")

    print()
    print("Add mcconsole to your PATH by adding this line to your shell profile:")
    print(f"  {{export_line}}")


def main() -> None:
    check_python_version()

    parser = argparse.ArgumentParser(description="Install the mcconsole CLI.")
    parser.add_argument(
        "install_dir",
        nargs="?",
        default=None,
        help="Install directory (default: ~/apps/mcconsole, prompted if omitted)",
    )
    args = parser.parse_args()

    install_dir = resolve_install_dir(args.install_dir)
    install_dir.mkdir(parents=True, exist_ok=True)
    print(f"Installing mcconsole to {{install_dir}} ...")

    src_dir = extract_bundle(install_dir)

    venv_dir = install_dir / "venv"
    create_venv(venv_dir)
    install_cli(venv_dir, src_dir)

    entry_point = venv_bin_dir(venv_dir) / ("mcconsole.exe" if os.name == "nt" else "mcconsole")
    add_to_path(entry_point.parent)

    print()
    print(f"mcconsole installed at {{entry_point}}")
    print(MOD_JAR_REMINDER)


if __name__ == "__main__":
    main()
'''


def render_bootstrap(bundle_bytes: bytes) -> str:
    bundle_b64 = base64.b64encode(bundle_bytes).decode("ascii")
    wrapped = "\n".join(textwrap.wrap(bundle_b64, width=100))
    return BOOTSTRAP_TEMPLATE.format(bundle_b64=wrapped)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        default=str(REPO_ROOT / "mcconsole-installer.py"),
        help="Output path for the generated installer (default: mcconsole-installer.py at repo root)",
    )
    args = parser.parse_args()

    if not CLI_DIR.is_dir():
        raise SystemExit(f"cli/ package not found at {CLI_DIR}")

    bundle_bytes = build_bundle_zip()
    script = render_bootstrap(bundle_bytes)

    output_path = Path(args.output).resolve()
    output_path.write_text(script)
    output_path.chmod(0o755)

    file_count = sum(1 for _ in iter_cli_files())
    print(f"Bundled {file_count} files from {CLI_DIR} ({len(bundle_bytes)} bytes zipped).")
    print(f"Wrote {output_path} ({output_path.stat().st_size} bytes).")


if __name__ == "__main__":
    main()
